### ISSUE TITLE
Auth document is not clear

### ISSUE THREAD

**Issue by mi096684** [GearPlug/dynamics365crm-python#3]
**Exchange the code for an access token:**
token = client.exchange_code('REDIRECT_URL', 'CODE')

in the above line, what is CODE?

token = client.refresh_token('REFRESH TOKEN', 'REDIRECT_URL')

What is REFRESH TOKEN, will help a lot

**Comment by ingmferrer** [comment]
Maybe this could help you.

https://github.com/GearPlug/dynamics365crm-python/issues/2#issuecomment-526734717

https://github.com/GearPlug/dynamics365crm-python/issues/2#issuecomment-528055820
