### ISSUE TITLE
Error on connection with access token

### ISSUE THREAD

**Issue by algot** [GearPlug/dynamics365crm-python#4]
I have token generated for my Dynamics org via external tool
I'm trying to connect to my org with this token but got an error

```
access_token = 'mytoken'
client = Client(resource='https://myorg.crm4.dynamics.com',
                token=access_token)
create_contact = client.create_contact(
    firstname="FIRSTNAME", lastname="LASTNAME", middlename="MIDDLENAME", emailaddress1="EMAILADDRESS")
```
I got following error

`Exception: The URL https://myorg.crm4.dynamics.com/api/data/v9.0/contacts retrieved and 403 error. Please check your credentials, make sure you have permission to perform this action and try again.`

Please suggest what is wrong with my code

**Comment by algot** [comment]
I changed my code according to code example

```
RESOURCE = 'https://myorg.crm4.dynamics.com'
ACCESS_TOKEN = 'mytoken'
client = Client(RESOURCE, ACCESS_TOKEN)
contacts = client.get_contacts(lastname='testlastname')
```

And I got following exception
Exception: To make petitions the token is necessary

**Comment by Arkaikus** [comment]
Hi, this should have been corrected with the last update using [Microsoft Authentication Library (MSAL)](https://github.com/AzureAD/microsoft-authentication-library-for-python), let us know if it still doesn't work. Best
