### ISSUE TITLE
What is the 'CODE ' that is required

### ISSUE THREAD

**Issue by Abdelkrim** [GearPlug/dynamics365crm-python#5]
to whom it may concern,

I would like to know what is the variable that is expected as a 'CODE' in the  README.MD

> Exchange the code for an access token 
> 
> token = client.exchange_code('REDIRECT_URL', 'CODE')

thank you for your help

**Comment by Arkaikus** [comment]
Hi, microsoft will send a temporal code to the especified callback in the query params to finish the oauth2 protocol, the method exchange_code needs it to obtain the json that contains the access_token, refresh_token, etc.

Best,
